# Generated by Django 4.2.11 on 2026-06-01 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lunchpost",
            name="view_count",
            field=models.PositiveIntegerField(default=0, verbose_name="浏览量"),
        ),
        migrations.CreateModel(
            name="PostView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="浏览时间"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_records",
                        to="store.lunchpost",
                        verbose_name="推荐",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_views",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="浏览用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "浏览记录",
                "verbose_name_plural": "浏览记录",
                "indexes": [
                    models.Index(
                        fields=["post", "user", "-viewed_at"],
                        name="store_postv_post_id_52665a_idx",
                    )
                ],
            },
        ),
    ]
