# Generated by Django 4.2.11 on 2026-06-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_add_view_count"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="postview",
            name="store_postv_post_id_52665a_idx",
        ),
        migrations.AddConstraint(
            model_name="postview",
            constraint=models.UniqueConstraint(
                fields=("post", "user"), name="unique_post_view_per_user"
            ),
        ),
    ]
