# Generated by Django 4.2.11 on 2026-06-01 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0003_unique_post_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="用户名快照"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("register", "用户注册"),
                            ("logout", "用户退出"),
                            ("admin_logout", "管理员退出"),
                            ("post_create", "发布推荐"),
                            ("post_delete", "删除推荐"),
                            ("comment_create", "发表评论"),
                            ("profile_update", "更新个人资料"),
                            ("password_change", "修改密码"),
                            ("admin_user_delete", "删除用户"),
                            ("admin_post_delete", "删除推荐(管理)"),
                            ("admin_comment_delete", "删除评论"),
                            ("admin_category_add", "添加分类"),
                            ("admin_category_edit", "编辑分类"),
                            ("admin_category_delete", "删除分类"),
                            ("admin_password_change", "管理员改密"),
                        ],
                        max_length=40,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "detail",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="操作详情"
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="对象类型"
                    ),
                ),
                (
                    "target_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="对象 ID"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 地址"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="浏览器/设备"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, verbose_name="登录账号")),
                (
                    "login_type",
                    models.CharField(
                        choices=[("user", "前台登录"), ("admin", "管理后台登录")],
                        max_length=10,
                        verbose_name="登录类型",
                    ),
                ),
                ("success", models.BooleanField(default=True, verbose_name="是否成功")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 地址"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="浏览器/设备"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登录时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "登录日志",
                "verbose_name_plural": "登录日志",
                "ordering": ["-created_at"],
            },
        ),
    ]
