# Generated by Django 4.2.11 on 2026-06-01 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0004_audit_logs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("register", "用户注册"),
                    ("logout", "用户退出"),
                    ("admin_logout", "管理员退出"),
                    ("post_create", "发布推荐"),
                    ("post_delete", "删除推荐"),
                    ("comment_create", "发表评论"),
                    ("profile_update", "更新个人资料"),
                    ("password_change", "修改密码"),
                    ("admin_user_delete", "删除用户"),
                    ("admin_post_delete", "删除推荐(管理)"),
                    ("admin_comment_delete", "删除评论"),
                    ("admin_category_add", "添加分类"),
                    ("admin_category_edit", "编辑分类"),
                    ("admin_category_delete", "删除分类"),
                    ("admin_password_change", "管理员改密"),
                    ("admin_announcement_add", "发布公告"),
                    ("admin_announcement_edit", "编辑公告"),
                    ("admin_announcement_delete", "删除公告"),
                ],
                max_length=40,
                verbose_name="操作类型",
            ),
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="公告标题")),
                ("content", models.TextField(verbose_name="公告内容")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否展示"),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="置顶显示"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发布人",
                    ),
                ),
            ],
            options={
                "verbose_name": "站点公告",
                "verbose_name_plural": "站点公告",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
    ]
