# Generated by Django 4.2.11 on 2026-06-01 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0005_announcement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("register", "用户注册"),
                    ("logout", "用户退出"),
                    ("admin_logout", "管理员退出"),
                    ("post_create", "发布推荐"),
                    ("post_delete", "删除推荐"),
                    ("comment_create", "发表评论"),
                    ("profile_update", "更新个人资料"),
                    ("password_change", "修改密码"),
                    ("admin_user_delete", "删除用户"),
                    ("admin_post_delete", "删除推荐(管理)"),
                    ("admin_comment_delete", "删除评论"),
                    ("admin_category_add", "添加分类"),
                    ("admin_category_edit", "编辑分类"),
                    ("admin_category_delete", "删除分类"),
                    ("admin_password_change", "管理员改密"),
                    ("admin_announcement_add", "发布公告"),
                    ("admin_announcement_edit", "编辑公告"),
                    ("admin_announcement_delete", "删除公告"),
                    ("admin_site_close", "关闭网站"),
                    ("admin_site_open", "开放网站"),
                ],
                max_length=40,
                verbose_name="操作类型",
            ),
        ),
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_site_open",
                    models.BooleanField(default=True, verbose_name="网站开放"),
                ),
                (
                    "closed_message_zh",
                    models.TextField(
                        blank=True,
                        default="网站维护中，暂停对外服务。如需处理事务请使用管理员账号登录后台。",
                        verbose_name="关站说明（中文）",
                    ),
                ),
                (
                    "closed_message_en",
                    models.TextField(
                        blank=True,
                        default="The site is under maintenance. Only administrators may log in.",
                        verbose_name="关站说明（英文）",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_config_updates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="最后操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "站点配置",
                "verbose_name_plural": "站点配置",
            },
        ),
    ]
