# Generated by Django 4.2.11 on 2026-06-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_site_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="beta_code_revision",
            field=models.PositiveIntegerField(default=0, verbose_name="邀请码版本"),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="beta_invite_code",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="内测邀请码"
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="is_beta_mode",
            field=models.BooleanField(default=False, verbose_name="内测模式"),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("register", "用户注册"),
                    ("logout", "用户退出"),
                    ("admin_logout", "管理员退出"),
                    ("post_create", "发布推荐"),
                    ("post_delete", "删除推荐"),
                    ("comment_create", "发表评论"),
                    ("profile_update", "更新个人资料"),
                    ("password_change", "修改密码"),
                    ("admin_user_delete", "删除用户"),
                    ("admin_post_delete", "删除推荐(管理)"),
                    ("admin_comment_delete", "删除评论"),
                    ("admin_category_add", "添加分类"),
                    ("admin_category_edit", "编辑分类"),
                    ("admin_category_delete", "删除分类"),
                    ("admin_password_change", "管理员改密"),
                    ("admin_announcement_add", "发布公告"),
                    ("admin_announcement_edit", "编辑公告"),
                    ("admin_announcement_delete", "删除公告"),
                    ("admin_site_close", "关闭网站"),
                    ("admin_site_open", "开放网站"),
                    ("admin_beta_on", "开启内测"),
                    ("admin_beta_off", "关闭内测"),
                    ("admin_beta_code", "更新内测邀请码"),
                ],
                max_length=40,
                verbose_name="操作类型",
            ),
        ),
    ]
