# Generated by Django 4.2.30 on 2026-06-01 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0007_beta_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_banned",
            field=models.BooleanField(default=False, verbose_name="封号"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_muted",
            field=models.BooleanField(default=False, verbose_name="禁言"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="login_restricted",
            field=models.BooleanField(default=False, verbose_name="限制登录"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="moderated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="处罚时间"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderation_actions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="处罚操作人",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="moderation_note",
            field=models.CharField(blank=True, max_length=500, verbose_name="处罚说明"),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("register", "用户注册"),
                    ("logout", "用户退出"),
                    ("admin_logout", "管理员退出"),
                    ("post_create", "发布推荐"),
                    ("post_delete", "删除推荐"),
                    ("comment_create", "发表评论"),
                    ("profile_update", "更新个人资料"),
                    ("password_change", "修改密码"),
                    ("admin_user_delete", "删除用户"),
                    ("admin_post_delete", "删除推荐(管理)"),
                    ("admin_comment_delete", "删除评论"),
                    ("admin_category_add", "添加分类"),
                    ("admin_category_edit", "编辑分类"),
                    ("admin_category_delete", "删除分类"),
                    ("admin_password_change", "管理员改密"),
                    ("admin_announcement_add", "发布公告"),
                    ("admin_announcement_edit", "编辑公告"),
                    ("admin_announcement_delete", "删除公告"),
                    ("admin_site_close", "关闭网站"),
                    ("admin_site_open", "开放网站"),
                    ("admin_beta_on", "开启内测"),
                    ("admin_beta_off", "关闭内测"),
                    ("admin_beta_code", "更新内测邀请码"),
                    ("admin_user_ban", "封禁用户"),
                    ("admin_user_unban", "解除封号"),
                    ("admin_user_mute", "禁言用户"),
                    ("admin_user_unmute", "解除禁言"),
                    ("admin_user_restrict_login", "限制用户登录"),
                    ("admin_user_allow_login", "解除登录限制"),
                ],
                max_length=40,
                verbose_name="操作类型",
            ),
        ),
    ]
