# Generated by Django 4.2.30 on 2026-06-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_user_moderation"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="contact_bilibili",
            field=models.URLField(blank=True, verbose_name="B站链接"),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="联系邮箱"
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="contact_github",
            field=models.URLField(blank=True, verbose_name="GitHub 链接"),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="contact_intro_en",
            field=models.TextField(
                blank=True,
                default="For reports, appeals, or inquiries, reach the site administrators via:",
                verbose_name="联系说明（英文）",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="contact_intro_zh",
            field=models.TextField(
                blank=True,
                default="如有违规举报、账号申诉或合作咨询，可通过以下方式联系站点管理员。",
                verbose_name="联系说明（中文）",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=30, verbose_name="联系电话"),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="contact_qq",
            field=models.CharField(blank=True, max_length=30, verbose_name="QQ"),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="contact_telegram",
            field=models.CharField(blank=True, max_length=80, verbose_name="Telegram"),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="contact_wechat",
            field=models.CharField(blank=True, max_length=80, verbose_name="微信号"),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="contact_weibo",
            field=models.URLField(blank=True, verbose_name="微博链接"),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="contact_xiaohongshu",
            field=models.URLField(blank=True, verbose_name="小红书链接"),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("register", "用户注册"),
                    ("logout", "用户退出"),
                    ("admin_logout", "管理员退出"),
                    ("post_create", "发布推荐"),
                    ("post_delete", "删除推荐"),
                    ("comment_create", "发表评论"),
                    ("profile_update", "更新个人资料"),
                    ("password_change", "修改密码"),
                    ("admin_user_delete", "删除用户"),
                    ("admin_post_delete", "删除推荐(管理)"),
                    ("admin_comment_delete", "删除评论"),
                    ("admin_category_add", "添加分类"),
                    ("admin_category_edit", "编辑分类"),
                    ("admin_category_delete", "删除分类"),
                    ("admin_password_change", "管理员改密"),
                    ("admin_announcement_add", "发布公告"),
                    ("admin_announcement_edit", "编辑公告"),
                    ("admin_announcement_delete", "删除公告"),
                    ("admin_site_close", "关闭网站"),
                    ("admin_site_open", "开放网站"),
                    ("admin_beta_on", "开启内测"),
                    ("admin_beta_off", "关闭内测"),
                    ("admin_beta_code", "更新内测邀请码"),
                    ("admin_user_ban", "封禁用户"),
                    ("admin_user_unban", "解除封号"),
                    ("admin_user_mute", "禁言用户"),
                    ("admin_user_unmute", "解除禁言"),
                    ("admin_user_restrict_login", "限制用户登录"),
                    ("admin_user_allow_login", "解除登录限制"),
                    ("admin_contact_update", "更新联系方式"),
                ],
                max_length=40,
                verbose_name="操作类型",
            ),
        ),
    ]
