# Generated by Django 4.2.30 on 2026-06-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_admin_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="foodcategory",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "情报分类",
                "verbose_name_plural": "情报分类",
            },
        ),
        migrations.AlterModelOptions(
            name="lunchpost",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "干饭情报",
                "verbose_name_plural": "干饭情报",
            },
        ),
    ]
