# Generated by Django 4.2.30 on 2026-06-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_rebrand_verbose_names"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="foodcategory",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "午餐分类",
                "verbose_name_plural": "午餐分类",
            },
        ),
        migrations.AlterModelOptions(
            name="lunchpost",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "午餐推荐",
                "verbose_name_plural": "午餐推荐",
            },
        ),
    ]
