# Generated by Django 4.2.30 on 2026-06-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_restore_verbose_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="站点名称")),
                ("url", models.URLField(max_length=500, verbose_name="链接地址")),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="简介"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="🔗", max_length=20, verbose_name="图标"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否展示"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "友情链接",
                "verbose_name_plural": "友情链接",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="foodcategory",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "情报分类",
                "verbose_name_plural": "情报分类",
            },
        ),
        migrations.AlterModelOptions(
            name="lunchpost",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "干饭情报",
                "verbose_name_plural": "干饭情报",
            },
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="friend_links_intro",
            field=models.TextField(
                blank=True,
                default="以下是与本站互相关注或推荐的友好站点，点击即可访问。",
                verbose_name="友链页说明",
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("register", "用户注册"),
                    ("logout", "用户退出"),
                    ("admin_logout", "管理员退出"),
                    ("post_create", "发布推荐"),
                    ("post_delete", "删除推荐"),
                    ("comment_create", "发表评论"),
                    ("profile_update", "更新个人资料"),
                    ("password_change", "修改密码"),
                    ("admin_user_delete", "删除用户"),
                    ("admin_post_delete", "删除推荐(管理)"),
                    ("admin_comment_delete", "删除评论"),
                    ("admin_category_add", "添加分类"),
                    ("admin_category_edit", "编辑分类"),
                    ("admin_category_delete", "删除分类"),
                    ("admin_password_change", "管理员改密"),
                    ("admin_announcement_add", "发布公告"),
                    ("admin_announcement_edit", "编辑公告"),
                    ("admin_announcement_delete", "删除公告"),
                    ("admin_site_close", "关闭网站"),
                    ("admin_site_open", "开放网站"),
                    ("admin_beta_on", "开启内测"),
                    ("admin_beta_off", "关闭内测"),
                    ("admin_beta_code", "更新内测邀请码"),
                    ("admin_user_ban", "封禁用户"),
                    ("admin_user_unban", "解除封号"),
                    ("admin_user_mute", "禁言用户"),
                    ("admin_user_unmute", "解除禁言"),
                    ("admin_user_restrict_login", "限制用户登录"),
                    ("admin_user_allow_login", "解除登录限制"),
                    ("admin_contact_update", "更新联系方式"),
                    ("admin_friend_link_add", "添加友链"),
                    ("admin_friend_link_edit", "编辑友链"),
                    ("admin_friend_link_delete", "删除友链"),
                ],
                max_length=40,
                verbose_name="操作类型",
            ),
        ),
    ]
