# Generated by Django 4.2.11 on 2026-06-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_reports_favorites_replies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("register", "用户注册"),
                    ("logout", "用户退出"),
                    ("admin_logout", "管理员退出"),
                    ("post_create", "发布推荐"),
                    ("post_edit", "编辑推荐"),
                    ("post_delete", "删除推荐"),
                    ("comment_create", "发表评论"),
                    ("report_create", "提交举报"),
                    ("appeal_create", "提交申诉"),
                    ("profile_update", "更新个人资料"),
                    ("password_change", "修改密码"),
                    ("admin_user_delete", "删除用户"),
                    ("admin_post_delete", "删除推荐(管理)"),
                    ("admin_post_edit", "编辑推荐(管理)"),
                    ("admin_comment_delete", "删除评论"),
                    ("admin_report_handle", "处理举报/申诉"),
                    ("admin_staff_create", "创建普通管理员"),
                    ("admin_staff_remove", "移除普通管理员"),
                    ("admin_staff_reset_password", "重置管理员密码"),
                    ("admin_category_add", "添加分类"),
                    ("admin_category_edit", "编辑分类"),
                    ("admin_category_delete", "删除分类"),
                    ("admin_password_change", "管理员改密"),
                    ("admin_announcement_add", "发布公告"),
                    ("admin_announcement_edit", "编辑公告"),
                    ("admin_announcement_delete", "删除公告"),
                    ("admin_site_close", "关闭网站"),
                    ("admin_site_open", "开放网站"),
                    ("admin_beta_on", "开启内测"),
                    ("admin_beta_off", "关闭内测"),
                    ("admin_beta_code", "更新内测邀请码"),
                    ("admin_user_ban", "封禁用户"),
                    ("admin_user_unban", "解除封号"),
                    ("admin_user_mute", "禁言用户"),
                    ("admin_user_unmute", "解除禁言"),
                    ("admin_user_restrict_login", "限制用户登录"),
                    ("admin_user_allow_login", "解除登录限制"),
                    ("admin_user_reset_password", "重置用户密码"),
                    ("admin_user_profile_update", "更新用户资料"),
                    ("admin_contact_update", "更新联系方式"),
                    ("admin_friend_link_add", "添加友链"),
                    ("admin_friend_link_edit", "编辑友链"),
                    ("admin_friend_link_delete", "删除友链"),
                ],
                max_length=40,
                verbose_name="操作类型",
            ),
        ),
    ]
